# DO NOT EDIT THIS FILE, IT IS GENERATED
#
# To change the contents of this file, edit
# phpBB/develop/create_schema_files.php and
# run it.
BEGIN TRANSACTION;

# Table: 'phpbb_blog_categories'
CREATE TABLE phpbb_blog_categories (
	id INTEGER PRIMARY KEY NOT NULL ,
	title varchar(255) NOT NULL DEFAULT '',
	description mediumtext(16777215) NOT NULL DEFAULT '',
	options INTEGER UNSIGNED NOT NULL DEFAULT '0',
	bitfield varchar(255) NOT NULL DEFAULT '',
	uid varchar(8) NOT NULL DEFAULT '',
	total_posts INTEGER UNSIGNED NOT NULL DEFAULT '0',
	last_post_id INTEGER UNSIGNED NOT NULL DEFAULT '0'
);


# Table: 'phpbb_blog_post_comments'
CREATE TABLE phpbb_blog_post_comments (
	id INTEGER PRIMARY KEY NOT NULL ,
	post_id INTEGER UNSIGNED NOT NULL DEFAULT '0',
	commenter_id INTEGER UNSIGNED NOT NULL DEFAULT '0',
	comment mediumtext(16777215) NOT NULL DEFAULT '',
	options INTEGER UNSIGNED NOT NULL DEFAULT '0',
	bitfield varchar(255) NOT NULL DEFAULT '',
	uid varchar(8) NOT NULL DEFAULT '',
	ctime INTEGER UNSIGNED NOT NULL DEFAULT '0'
);

CREATE INDEX phpbb_blog_post_comments_post ON phpbb_blog_post_comments (post_id);
CREATE INDEX phpbb_blog_post_comments_ctime ON phpbb_blog_post_comments (ctime);

# Table: 'phpbb_blog_posts'
CREATE TABLE phpbb_blog_posts (
	id INTEGER PRIMARY KEY NOT NULL ,
	category INTEGER UNSIGNED NOT NULL DEFAULT '0',
	title varchar(255) NOT NULL DEFAULT '',
	poster_id INTEGER UNSIGNED NOT NULL DEFAULT '0',
	post mediumtext(16777215) NOT NULL DEFAULT '',
	options INTEGER UNSIGNED NOT NULL DEFAULT '0',
	bitfield varchar(255) NOT NULL DEFAULT '',
	uid varchar(8) NOT NULL DEFAULT '',
	ptime INTEGER UNSIGNED NOT NULL DEFAULT '0',
	read_count INTEGER UNSIGNED NOT NULL DEFAULT '0',
	last_edit_time INTEGER UNSIGNED NOT NULL DEFAULT '0',
	edit_count INTEGER UNSIGNED NOT NULL DEFAULT '0',
	comment_count INTEGER UNSIGNED NOT NULL DEFAULT '0',
	comment_lock INTEGER UNSIGNED NOT NULL DEFAULT '0'
);

CREATE INDEX phpbb_blog_posts_category ON phpbb_blog_posts (category);
CREATE INDEX phpbb_blog_posts_poster ON phpbb_blog_posts (poster_id);
CREATE INDEX phpbb_blog_posts_ptime ON phpbb_blog_posts (ptime);

# Table: 'phpbb_blog_tags'
CREATE TABLE phpbb_blog_tags (
	id INTEGER PRIMARY KEY NOT NULL ,
	tag varchar(255) NOT NULL DEFAULT '',
	tag_count INTEGER UNSIGNED NOT NULL DEFAULT '0'
);



COMMIT;