# DO NOT EDIT THIS FILE, IT IS GENERATED
#
# To change the contents of this file, edit
# phpBB/develop/create_schema_files.php and
# run it.

# Table: 'phpbb_blog_categories'
CREATE TABLE phpbb_blog_categories (
	id INTEGER NOT NULL,
	name VARCHAR(255) CHARACTER SET UTF8 DEFAULT '' NOT NULL COLLATE UNICODE,
	description BLOB SUB_TYPE TEXT CHARACTER SET UTF8 DEFAULT '' NOT NULL,
	options INTEGER DEFAULT 7 NOT NULL,
	bitfield VARCHAR(255) CHARACTER SET NONE DEFAULT '' NOT NULL,
	uid VARCHAR(8) CHARACTER SET NONE DEFAULT '' NOT NULL,
	total_posts INTEGER DEFAULT 0 NOT NULL,
	last_post_id INTEGER DEFAULT 0 NOT NULL
);;

ALTER TABLE phpbb_blog_categories ADD PRIMARY KEY (id);;


CREATE GENERATOR phpbb_blog_categories_gen;;
SET GENERATOR phpbb_blog_categories_gen TO 0;;

CREATE TRIGGER t_phpbb_blog_categories FOR phpbb_blog_categories
BEFORE INSERT
AS
BEGIN
	NEW.id = GEN_ID(phpbb_blog_categories_gen, 1);
END;;


# Table: 'phpbb_blog_posts'
CREATE TABLE phpbb_blog_posts (
	id INTEGER NOT NULL,
	category INTEGER DEFAULT 0 NOT NULL,
	title VARCHAR(255) CHARACTER SET UTF8 DEFAULT '' NOT NULL COLLATE UNICODE,
	poster_id INTEGER DEFAULT 0 NOT NULL,
	post BLOB SUB_TYPE TEXT CHARACTER SET UTF8 DEFAULT '' NOT NULL,
	options INTEGER DEFAULT 7 NOT NULL,
	bitfield VARCHAR(255) CHARACTER SET NONE DEFAULT '' NOT NULL,
	uid VARCHAR(8) CHARACTER SET NONE DEFAULT '' NOT NULL,
	post_time INTEGER DEFAULT 0 NOT NULL
);;

ALTER TABLE phpbb_blog_posts ADD PRIMARY KEY (id);;

CREATE INDEX phpbb_blog_posts_category ON phpbb_blog_posts(category);;

CREATE GENERATOR phpbb_blog_posts_gen;;
SET GENERATOR phpbb_blog_posts_gen TO 0;;

CREATE TRIGGER t_phpbb_blog_posts FOR phpbb_blog_posts
BEFORE INSERT
AS
BEGIN
	NEW.id = GEN_ID(phpbb_blog_posts_gen, 1);
END;;


