/*
 * DO NOT EDIT THIS FILE, IT IS GENERATED
 *
 * To change the contents of this file, edit
 * phpBB/develop/create_schema_files.php and
 * run it.
 */

/*
	Table: 'phpbb_blog_categories'
*/
CREATE TABLE [phpbb_blog_categories] (
	[id] [int] IDENTITY (1, 1) NOT NULL ,
	[name] [varchar] (255) DEFAULT ('') NOT NULL ,
	[description] [varchar] (4000) DEFAULT ('') NOT NULL ,
	[options] [int] DEFAULT (7) NOT NULL ,
	[bitfield] [varchar] (255) DEFAULT ('') NOT NULL ,
	[uid] [varchar] (8) DEFAULT ('') NOT NULL ,
	[total_posts] [int] DEFAULT (0) NOT NULL ,
	[last_post_id] [int] DEFAULT (0) NOT NULL 
) ON [PRIMARY]
GO

ALTER TABLE [phpbb_blog_categories] WITH NOCHECK ADD 
	CONSTRAINT [PK_phpbb_blog_categories] PRIMARY KEY  CLUSTERED 
	(
		[id]
	)  ON [PRIMARY] 
GO


/*
	Table: 'phpbb_blog_posts'
*/
CREATE TABLE [phpbb_blog_posts] (
	[id] [int] IDENTITY (1, 1) NOT NULL ,
	[category] [int] DEFAULT (0) NOT NULL ,
	[title] [varchar] (255) DEFAULT ('') NOT NULL ,
	[poster_id] [int] DEFAULT (0) NOT NULL ,
	[post] [text] DEFAULT ('') NOT NULL ,
	[options] [int] DEFAULT (7) NOT NULL ,
	[bitfield] [varchar] (255) DEFAULT ('') NOT NULL ,
	[uid] [varchar] (8) DEFAULT ('') NOT NULL ,
	[post_time] [int] DEFAULT (0) NOT NULL 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [phpbb_blog_posts] WITH NOCHECK ADD 
	CONSTRAINT [PK_phpbb_blog_posts] PRIMARY KEY  CLUSTERED 
	(
		[id]
	)  ON [PRIMARY] 
GO

CREATE  INDEX [category] ON [phpbb_blog_posts]([category]) ON [PRIMARY]
GO


