#
# This dump is for referance only!
#
# ************************************************************
# DO NOT EDIT THIS FILE, IT IS GENERATED
#
# To change the contents of this file, edit
# phpBB/develop/create_schema_files.php and
# run it.
# Table: 'phpbb_blog_categories'
CREATE TABLE phpbb_blog_categories (
	id mediumint(8) UNSIGNED NOT NULL auto_increment,
	name varchar(255) DEFAULT '' NOT NULL,
	description mediumtext NOT NULL,
	options int(11) UNSIGNED DEFAULT '0' NOT NULL,
	bitfield varchar(255) DEFAULT '' NOT NULL,
	uid varchar(8) DEFAULT '' NOT NULL,
	total_posts mediumint(8) UNSIGNED DEFAULT '0' NOT NULL,
	last_post_id mediumint(8) UNSIGNED DEFAULT '0' NOT NULL,
	PRIMARY KEY (id)
) CHARACTER SET `utf8` COLLATE `utf8_bin`;

# Table: 'phpbb_blog_posts'
CREATE TABLE phpbb_blog_posts (
	id int(11) UNSIGNED NOT NULL auto_increment,
	category int(11) UNSIGNED DEFAULT '0' NOT NULL,
	title varchar(255) DEFAULT '' NOT NULL,
	poster_id int(11) UNSIGNED DEFAULT '0' NOT NULL,
	post mediumtext NOT NULL,
	options int(11) UNSIGNED DEFAULT '0' NOT NULL,
	bitfield varchar(255) DEFAULT '' NOT NULL,
	uid varchar(8) DEFAULT '' NOT NULL,
	ptime int(11) UNSIGNED DEFAULT '0' NOT NULL,
	PRIMARY KEY (id),
	KEY category (category),
	KEY poster (poster_id),
	KEY ptime (ptime)
) CHARACTER SET `utf8` COLLATE `utf8_bin`;
