# DO NOT EDIT THIS FILE, IT IS GENERATED
#
# To change the contents of this file, edit
# phpBB/develop/create_schema_files.php and
# run it.
BEGIN TRANSACTION;

# Table: 'phpbb_blog_categories'
CREATE TABLE phpbb_blog_categories (
	id INTEGER PRIMARY KEY NOT NULL ,
	name varchar(255) NOT NULL DEFAULT '',
	description text(65535) NOT NULL DEFAULT '',
	options INTEGER UNSIGNED NOT NULL DEFAULT '7',
	bitfield varchar(255) NOT NULL DEFAULT '',
	uid varchar(8) NOT NULL DEFAULT '',
	total_posts INTEGER UNSIGNED NOT NULL DEFAULT '0',
	last_post_id INTEGER UNSIGNED NOT NULL DEFAULT '0'
);


# Table: 'phpbb_blog_posts'
CREATE TABLE phpbb_blog_posts (
	id INTEGER PRIMARY KEY NOT NULL ,
	category INTEGER UNSIGNED NOT NULL DEFAULT '0',
	title varchar(255) NOT NULL DEFAULT '',
	poster_id INTEGER UNSIGNED NOT NULL DEFAULT '0',
	post mediumtext(16777215) NOT NULL DEFAULT '',
	options INTEGER UNSIGNED NOT NULL DEFAULT '7',
	bitfield varchar(255) NOT NULL DEFAULT '',
	uid varchar(8) NOT NULL DEFAULT '',
	post_time INTEGER UNSIGNED NOT NULL DEFAULT '0'
);

CREATE INDEX phpbb_blog_posts_category ON phpbb_blog_posts (category);


COMMIT;